<a href="https://colab.research.google.com/github/wbandabarragan/quantum-mechanics-1/blob/main/python-tools/python_for_QM08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tutorial 8: Python for Quantum Mechanics

## Exercise: solving eigenvalue problems

$$\newcommand{\ket}[1]{\left|{#1}\right\rangle}$$
$$\newcommand{\bra}[1]{\left\langle{#1}\right|}$$
$$\newcommand{\braket}[2]{\left\langle{#1}\middle|{#2}\right\rangle}$$

Consider a quantum system in a state, $\ket{\Psi}$:

$\Psi = \frac{1}{\sqrt{3}}\left[\begin{array}{@{}c@{}}
    i \\
    -i \\
    i
    \end{array} \right]$
    
The Hamiltonian is represented by the matrix shown below:


$\hat{H} = \left[\begin{array}{@{ }c@{\kern2em} c@{\kern2em} c@{ }}
2 & 1 & 0\\
1 & 2 & 0\\
0 & 0 & 3
\end{array} \right]$

(a) Determine the eigenvalues and eigenvectors of $\hat{H}$. What do the eigenvalues represent?


(b) Which eigenvalue of $\hat{H}$ is most likely to emerge from a measurement?


(c) Find $\langle H \rangle$, $\langle H^2 \rangle$, and $\sigma_H$.


### Solution:

(a) Determine the eigenvalues and eigenvectors of $\hat{H}$. What do the eigenvalues represent?

$\hat{H} = \left[\begin{array}{@{ }c@{\kern2em} c@{\kern2em} c@{ }}
2 & 1 & 0\\
1 & 2 & 0\\
0 & 0 & 3
\end{array} \right]$

In [1]:
import numpy as np

In [5]:
# Define the matrix for H

hamiltonian_matrix = np.array([[2., 1., 0.], [1., 2., 0.], [0., 0., 3.]])

print(hamiltonian_matrix)
print("\n")
print(hamiltonian_matrix.shape)

[[2. 1. 0.]
 [1. 2. 0.]
 [0. 0. 3.]]


(3, 3)


In [6]:
# Calculate the eigenvalues and eigenvectors np.linalg.eig(M)

w_eigenvalues, v_eigvectors = np.linalg.eig(hamiltonian_matrix)

print("Eigenvalue 1: ", w_eigenvalues[0], "with corresponding eigenvector 1: ", v_eigvectors[0])
print("Eigenvalue 2: ", w_eigenvalues[1], "with corresponding eigenvector 2: ", v_eigvectors[1])
print("Eigenvalue 3: ", w_eigenvalues[2], "with corresponding eigenvector 3: ", v_eigvectors[2])

Eigenvalue 1:  3.0 with corresponding eigenvector 1:  [ 0.70710678 -0.70710678  0.        ]
Eigenvalue 2:  1.0 with corresponding eigenvector 2:  [0.70710678 0.70710678 0.        ]
Eigenvalue 3:  3.0 with corresponding eigenvector 3:  [0. 0. 1.]


(b) Which eigenvalue of $\hat{H}$ is most likely to emerge from a measurement?

$\Psi = \frac{1}{\sqrt{3}}\left[\begin{array}{@{}c@{}}
    i \\
    -i \\
    i
    \end{array} \right]$



In [7]:
print(1.j**2)

(-1+0j)


In [11]:
# We need the wave function -> probabilities

# Define psi

psi = np.array([1.j/np.sqrt(3.), -1.j/np.sqrt(3.), 1.j/np.sqrt(3.)])

print(psi)
print("\n")
print("Norm of psi: ", np.linalg.norm(psi))

[ 0.+0.57735027j -0.-0.57735027j  0.+0.57735027j]


Norm of psi:  1.0


In [12]:
# Get the eigenvectors:

vector_0 = v_eigvectors[0]
vector_1 = v_eigvectors[1]
vector_2 = v_eigvectors[2]


In [13]:
# Get the probabilities

prob_0 = np.abs(np.dot(vector_0, psi)**2/np.dot(psi,psi))
prob_1 = np.abs(np.dot(vector_1, psi)**2/np.dot(psi,psi))
prob_2 = np.abs(np.dot(vector_2, psi)**2/np.dot(psi,psi))

print(prob_0, prob_1, prob_2)

0.6666666666666665 0.0 0.33333333333333337


The most likely energy/state to emerge is the first one, so $E_1$

In [14]:
print("Most likely eigenvalue 1: ", w_eigenvalues[0], "with corresponding eigenvector 1: ", v_eigvectors[0])

Most likely eigenvalue 1:  3.0 with corresponding eigenvector 1:  [ 0.70710678 -0.70710678  0.        ]



(c) Find $\langle H \rangle$, $\langle H^2 \rangle$, and $\sigma_H$.


$\langle H \rangle$ = $\langle \psi | H | \psi \rangle$

In [15]:
# Calculate the expectation value

h_expectation = np.abs(np.dot(np.dot(np.conjugate(psi), hamiltonian_matrix), psi.T))

print(h_expectation)

1.666666666666667


$\langle H^2 \rangle$ = $\langle \psi | H^2 | \psi \rangle$

In [16]:
# Calculate the expectation value

h2_expectation = np.abs(np.dot(np.dot(np.conjugate(psi), hamiltonian_matrix @ hamiltonian_matrix), psi.T))

print(h2_expectation)

3.666666666666668


### Uncertainty:

$\sigma_H = \sqrt{\langle H^2 \rangle - \langle H\rangle^2}$

In [17]:
sigma_h = np.sqrt(h2_expectation - h_expectation**2)

print(sigma_h)

0.9428090415820636
