<a href="https://colab.research.google.com/github/wbandabarragan/quantum-mechanics-1/blob/main/python-notebooks/python4QM_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tutorial 8: Python for Quantum Mechanics

## Exercise: Find probabilities

$$\newcommand{\ket}[1]{\left|{#1}\right\rangle}$$
$$\newcommand{\bra}[1]{\left\langle{#1}\right|}$$
$$\newcommand{\braket}[2]{\left\langle{#1}\middle|{#2}\right\rangle}$$

Consider a quantum system in a state, $\ket{\Psi}$:

$\Psi = \frac{1}{\sqrt{3}}\left[\begin{array}{@{}c@{}}
    +i \\
    -i \\
    +i
    \end{array} \right]$
    
The Hamiltonian is represented by the matrix shown below:


$\hat{H} = \left[\begin{array}{@{ }c@{\kern2em} c@{\kern2em} c@{ }}
2 & 1 & 0\\
1 & 2 & 0\\
0 & 0 & 3
\end{array} \right]$

(a) Determine the eigenvalues and eigenvectors of $\hat{H}$. What do the eigenvalues represent?


(b) Which eigenvalue of $\hat{H}$ is most likely to emerge from a measurement? Hint: Calculate probabilities.


(c) Find $\langle H \rangle$, $\langle H^2 \rangle$, and $\sigma_H$.


### (a) Determine the eigenvalues and eigenvectors of $\hat{H}$. What do the eigenvalues represent?


$\hat{H} = \left[\begin{array}{@{ }c@{\kern2em} c@{\kern2em} c@{ }}
2 & 1 & 0\\
1 & 2 & 0\\
0 & 0 & 3
\end{array} \right]$

#### Ref: https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html#

In [1]:
# Importing libraries
import numpy as np

In [4]:
# Define Hamiltonian matrix:

h_matrix = np.array([[2., 1., 0.], [1., 2., 0.], [0., 0., 3.]])

print("Hamiltonian :\n",  h_matrix)

Hamiltonian :
 [[2. 1. 0.]
 [1. 2. 0.]
 [0. 0. 3.]]


In [6]:
# Safe checks:
print(h_matrix.shape, h_matrix.size)

(3, 3) 9


In [8]:
# Compute the eigenvalues and corresponding eigenvectors

e_values, e_vectors = np.linalg.eig(h_matrix)

In [15]:
# Print the results
print("Energy eigenvalues: \n", e_values)

print("E1 = ", e_values[0])
print("E2 = ", e_values[1])
print("E3 = ", e_values[2])

Energy eigenvalues: 
 [3. 1. 3.]
E1 =  3.0
E2 =  1.0
E3 =  3.0


### What do the eigenvalues represent?

They represent possible values for measurements of E.

We see quantisation ${E_n}$.

We have degenerate states.

In [16]:
# Print the results
print("Energy eigenvectors: \n", e_vectors)

print("psi1 = ", e_vectors[0])
print("psi2 = ", e_vectors[1])
print("psi3 = ", e_vectors[2])

Energy eigenvectors: 
 [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
psi1 =  [ 0.70710678 -0.70710678  0.        ]
psi2 =  [0.70710678 0.70710678 0.        ]
psi3 =  [0. 0. 1.]


In [20]:
#float(np.sqrt(2)/2)

In [26]:
# Print the results
print("E1 = ", e_values[0], ", psi1 = ", e_vectors[0])
print("\n")
print("E2 = ", e_values[1], ", psi2 = ", e_vectors[1])
print("\n")
print("E3 = ", e_values[2], ", psi3 = ", e_vectors[2])

E1 =  3.0 , psi1 =  [ 0.70710678 -0.70710678  0.        ]


E2 =  1.0 , psi2 =  [0.70710678 0.70710678 0.        ]


E3 =  3.0 , psi3 =  [0. 0. 1.]


In [33]:
# Safe check: orthogonality

d12 = np.dot(e_vectors[0], e_vectors[1])
d13 = np.dot(e_vectors[0], e_vectors[2]) # -> Share the same E_1 = E_3 = 3
d23 = np.dot(e_vectors[1], e_vectors[2])

print(d12, d13, d23)

0.0 0.0 0.0


In [34]:
# Safe check: normalisation

n11 = np.dot(e_vectors[0], e_vectors[0])
n22 = np.dot(e_vectors[1], e_vectors[1])
n33 = np.dot(e_vectors[2], e_vectors[2])

print(round(n11, 5), round(n22, 5), round(n33, 5))

1.0 1.0 1.0


### (b) Which eigenvalue of $\hat{H}$ is most likely to emerge from a measurement? Hint: Calculate probabilities.

$\Psi = \frac{1}{\sqrt{3}}\left[\begin{array}{@{}c@{}}
    +i \\
    -i \\
    +i
    \end{array} \right]$

Compute probabilities:

$P (E_{\rm n})= |\langle v_{\rm n}|\Psi\rangle|^2/|\langle \Psi|\Psi\rangle|^2$

In [41]:
# Define psi, i = \sqrt(-1) -> .j
psi = np.array([+1.j/np.sqrt(3), -1.j/np.sqrt(3), +1.j/np.sqrt(3)])
print(psi)

# Safe check: normalised?

# First way
npp = abs(np.dot(psi, psi))

print("Norm of psi: " , round(npp.real, 5))

# Second way -> norm
print("Norm of psi: " , np.linalg.norm(psi))

[ 0.+0.57735027j -0.-0.57735027j  0.+0.57735027j]
Norm of psi:  1.0
Norm of psi:  1.0


 We see that $\psi$ is normalised!

In [46]:
# Get the probabilities

prob_1 = np.abs(np.dot(e_vectors[0], psi)**2)
prob_2 = np.abs(np.dot(e_vectors[1], psi)**2)
prob_3 = np.abs(np.dot(e_vectors[2], psi)**2)

print("Prob (E1) = ", round(prob_1, 5))
print("\n")
print("Prob (E2) = ", round(prob_2, 5))
print("\n")
print("Prob (E3) = ", round(prob_3, 5))

Prob (E1) =  0.66667


Prob (E2) =  0.0


Prob (E3) =  0.33333


### Notes:

- Answer: $E_1$ is most likely to emerge in measurement!

- $E_2$ cannot emerge for the state:

$\Psi = \frac{1}{\sqrt{3}}\left[\begin{array}{@{}c@{}}
    +i \\
    -i \\
    +i
    \end{array} \right]$

because of orthogonality $\langle v_2|\Psi\rangle$.

### (c) Find $\langle H \rangle$, $\langle H^2 \rangle$, and $\sigma_H$.

#### Expectation values:

$\langle H \rangle = \int \psi^* \hat H \psi dx = \langle \psi | \hat H | \psi\rangle$


$\langle H^2 \rangle = \int \psi^* H^2 \psi dx = \langle \psi | H^2 | \psi\rangle$


In [53]:
# Expectation value of H
h_exp = abs(np.dot(np.dot(np.conjugate(psi), h_matrix), psi.T))

print("Expectation value of H: ", round(h_exp, 5))
print("\n")

# Expectation value of H
h_exp2 = abs(np.dot(np.dot(np.conjugate(psi), h_matrix @ h_matrix), psi.T))

print("Expectation value of H: ", round(h_exp2, 5))

Expectation value of H:  1.66667


Expectation value of H:  3.66667


#### Energy uncertainty:

$\sigma_H = \sqrt{\langle H^2 \rangle - \langle H \rangle^2}$

In [55]:
# Uncertainty in H

sigma_h = np.sqrt(h_exp2 - h_exp**2)

print("Uncertainty in H: ", round(sigma_h, 5))

Uncertainty in H:  0.94281


### Note:

$\Psi$ is not a stationary state.

## Exercise: Expectation value of an operator

Consider a normalized quantum state:

$$
|\Psi\rangle = \frac{1}{\sqrt{2}} \begin{pmatrix} 1 \\ i \end{pmatrix},
$$

and a Hermitian operator (observable):

$$
\hat{A} = \begin{pmatrix} 1 & 2 \\ 2 & 3 \end{pmatrix}.
$$

1. Is $A$ Hermitian?

2.  The expectation value $\langle A \rangle = \langle \Psi | \hat{A} | \Psi \rangle$

3.  The expectation value $\langle A^2 \rangle = \langle \Psi | \hat{A}^2 | \Psi \rangle$

4.  The uncertainty $\sigma_A = \sqrt{\langle A^2 \rangle - \langle A \rangle^2}$

### 1. Is $A$ Hermitian?

In [60]:
# Define the matrix A

a_matrix = np.array([[1, 2], [2, 3]])

print("A = \n", a_matrix)

print(a_matrix.shape)

A = 
 [[1 2]
 [2 3]]
(2, 2)


In [62]:
# Conjugate of the matrix
a_conj = a_matrix.conj()

a_dag  = a_conj.T
print(a_dag)

[[1 2]
 [2 3]]


### Compare matrix elements with ``np.allclose``

https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

In [64]:
print("Is A Hermitian?", np.allclose(a_matrix, a_dag))

Is A Hermitian? True


### 2.  The expectation value $\langle A \rangle = \langle \Psi | \hat{A} | \Psi \rangle$


where:

$$
|\Psi\rangle = \frac{1}{\sqrt{2}} \begin{pmatrix} 1 \\ i \end{pmatrix},
$$

In [68]:
# Define psi

psi_2 = np.array([[1.], [1.j]])/np.sqrt(2)

print(psi_2)

[[0.70710678+0.j        ]
 [0.        +0.70710678j]]


In [75]:
# Expectation values using vdot

a_exp  = abs(np.vdot(psi_2, a_matrix @ psi_2))
a_exp2 = abs(np.vdot(psi_2, a_matrix @ ( a_matrix @ psi_2)))

print("Expectation value of A: ", round(a_exp, 5))
print("\n")
print("Expectation value of A^2: ", round(a_exp2, 5))

Expectation value of A:  2.0


Expectation value of A^2:  9.0


### 4.  The uncertainty:

 $\sigma_A = \sqrt{\langle A^2 \rangle - \langle A \rangle^2}$

In [76]:
sigma_a = np.sqrt(a_exp2 - a_exp**2)

print("Uncertainty in A: ", round(sigma_a, 5))

Uncertainty in A:  2.23607


Imagine A is H:

$\sigma_A = \Delta E$

Energy-time uncertainty principle:

$$\Delta E\,\Delta t\geq \frac{\hbar}{2}$$